# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-04 16:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_navigation', '0002_navigationplugin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menucontent',
            name='title',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='menu_content',
        ),
        migrations.AddField(
            model_name='menucontent',
            name='root',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='djangocms_navigation.MenuItem'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
