# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-11 10:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_navigation', '0003_changes_for_versioning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menucontent',
            name='root',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='djangocms_navigation.MenuItem'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
