# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-11 11:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_navigation', '0004_auto_20190111_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationplugin',
            name='menu',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='djangocms_navigation.Menu'),
            preserve_default=False,
        ),
    ]
