# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-10 08:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_navigation', '0005_navigationplugin_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='djangocms_navigation_menu_site', to='sites.Site'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='djangocms_navigation_menuitem_content_type', to='contenttypes.ContentType'),
        ),
        migrations.AlterUniqueTogether(
            name='menu',
            unique_together=set([]),
        ),
    ]
