# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-03-02 08:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('djangocms_navigation', '0006_auto_20190410_0855'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='menu',
            unique_together=set([('identifier', 'site')]),
        ),
    ]
