# Generated by Django 2.2.14 on 2020-08-07 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_navigation', '0011_menuitem_soft_root'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='hide_node',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Hide node in navigation'),
        ),
    ]
