# Generated by Django 2.2.14 on 2020-08-20 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_navigation', '0012_menuitem_hide_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='is_home',
            field=models.BooleanField(db_index=True, default=False, verbose_name='is home'),
        ),
    ]
